name: CI Workflow

on: [push]

# FIX: Change 'job:' to 'jobs:' at the top level
jobs:  
  my_build_job: # You need an identifier for your job here
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4